
all:
	gcc -c PromTool.c -o ./obj/PromTool.o -mwindows -Wall -Wextra -pedantic -DUNICODE -mthreads -D_MT
	gcc ./obj/PromTool.o -o PromTool.exe -mwindows -Wall -Wextra -pedantic -DUNICODE -mthreads -D_MT

